#ifndef __TIMER_ID_H__
#define __TIMER_ID_H__

/* TIMER - MS */
enum
{
    /* HAL SERIAL */
    TIMER_ID_UART_0_TX_DONE,
    TIMER_ID_UART_0_RX,

    TIMER_ID_UART_1_TX_DONE,
    TIMER_ID_UART_1_RX,

    TIMER_ID_UART_2_TX_DONE,
    TIMER_ID_UART_2_RX,

    TIMER_ID_UART_3_TX_DONE,
    TIMER_ID_UART_3_RX,

    /* PARSER */
    TIMER_ID_COMM_FRONT_TX,

    /* QUEUE */
    TIMER_ID_QUEUE_RETRY_WAIT,

    /* SYSTEM */
    TIMER_ID_1MS,
    TIMER_ID_10MS,
    TIMER_ID_100MS,
    TIMER_ID_1SEC,
    TIMER_ID_40SEC,
    TIMER_ID_1MIN,


    MAX_TIMER_ID_NUM
};

#endif /* __TIMER_ID_H__ */
