#ifndef __TIMER_ID_H__
#define __TIMER_ID_H__

/* TIMER - MS */
enum
{
    TIMER_ID_COMM_MAIN_RX,
    TIMER_ID_COMM_MAIN_TX,

    TIMER_ID_COMM_KEY_RX,
    TIMER_ID_COMM_KEY_TX,


    TIMER_ID_UART_0_TX_DONE,
    TIMER_ID_UART_1_TX_DONE,
    TIMER_ID_UART_2_TX_DONE,
    TIMER_ID_UART_3_TX_DONE,
    TIMER_ID_UART_0_RX,
    TIMER_ID_UART_1_RX,
    TIMER_ID_UART_2_RX,
    TIMER_ID_UART_3_RX,
    TIMER_ID_COMM_WAIT_1,
    TIMER_ID_COMM_WAIT_2,
    TIMER_ID_COMM_WAIT_3,
    TIMER_ID_COMM_WAIT_4,

    TIMER_ID_COMM_TX_COMPLETE_1,
    TIMER_ID_1MS,
    TIMER_ID_10MS,
    TIMER_ID_100MS,

    MAX_TIMER_ID_NUM
};

#endif /* __TIMER_ID_H__ */
